/**
 * OrgOS — export the local SQLite demo dataset to a Cloudflare D1 seed SQL file.
 *
 * Usage:
 *   bun run scripts/export-d1-seed.ts [sqlite-db-path] [output-sql-path]
 *   (defaults: db/custom.db → cloudflare/seed/seed-demo.sql)
 *
 * Apply on Cloudflare:
 *   npx wrangler d1 execute orgos --config wrangler.jsonc \
 *     --remote --file=cloudflare/seed/seed-demo.sql
 *
 * The script:
 *   • reads every user table from the local SQLite file,
 *   • orders tables by foreign-key dependencies (children after parents),
 *     with per-row topological ordering for self-referencing columns
 *     (Task.parentTaskId, Department.parentId, Membership.managerId),
 *   • emits idempotent SQL: DELETE FROM in reverse dependency order,
 *     then multi-row INSERTs (200 rows per statement).
 */
import { Database } from 'bun:sqlite'
import { mkdirSync, writeFileSync } from 'fs'
import { dirname } from 'path'

const dbPath = process.argv[2] ?? 'db/custom.db'
const outPath = process.argv[3] ?? 'cloudflare/seed/seed-demo.sql'

const db = new Database(dbPath, { readonly: true })

const EXCLUDED = new Set(['sqlite_sequence', '__cf_d1_migrations'])

const tables = (
  db
    .query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
    .all() as { name: string }[]
)
  .map((t) => t.name)
  .filter((t) => !t.startsWith('sqlite_') && !EXCLUDED.has(t))

interface FkRow {
  id: number
  seq: number
  table: string
  from: string
  to: string
}
interface ColRow {
  name: string
  pk: number
}

const fks = new Map<string, FkRow[]>()
const cols = new Map<string, ColRow[]>()
for (const t of tables) {
  fks.set(t, db.query(`PRAGMA foreign_key_list("${t}")`).all() as FkRow[])
  cols.set(t, db.query(`PRAGMA table_info("${t}")`).all() as ColRow[])
}

// ---- topological order: parents (referenced tables) first ----
const order: string[] = []
const visited = new Set<string>()
function visit(t: string, stack: Set<string>) {
  if (visited.has(t)) return
  if (stack.has(t)) throw new Error(`foreign-key cycle involving "${t}"`)
  stack.add(t)
  for (const fk of fks.get(t) ?? []) {
    if (fk.table !== t && tables.includes(fk.table)) visit(fk.table, stack)
  }
  stack.delete(t)
  visited.add(t)
  order.push(t)
}
for (const t of tables) visit(t, new Set())

// ---- per-row ordering for self-references (parent rows first) ----
function rowsForTable(t: string): Array<Record<string, unknown>> {
  const rows = db.query(`SELECT * FROM "${t}"`).all() as Array<Record<string, unknown>>
  const selfFks = (fks.get(t) ?? []).filter((fk) => fk.table === t)
  if (!selfFks.length || rows.length < 2) return rows

  const pk = cols.get(t)!.find((c) => c.pk === 1)?.name
  if (!pk) return rows // composite/no pk — nothing to order by
  const byPk = new Map<string, Record<string, unknown>>()
  for (const r of rows) byPk.set(String(r[pk]), r)

  const out: Array<Record<string, unknown>> = []
  const emitted = new Set<string>()
  const emit = (r: Record<string, unknown>) => {
    const id = String(r[pk])
    if (emitted.has(id)) return
    emitted.add(id)
    for (const fk of selfFks) {
      const parent = r[fk.from] != null ? byPk.get(String(r[fk.from])) : null
      if (parent) emit(parent)
    }
    out.push(r)
  }
  for (const r of rows) emit(r)
  return out
}

// ---- SQL literal formatting ----
function val(v: unknown): string {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'number' || typeof v === 'bigint') return String(v)
  if (typeof v === 'boolean') return v ? '1' : '0'
  if (typeof v === 'string') return `'${v.replace(/'/g, "''")}'`
  return `'${String(v).replace(/'/g, "''")}'`
}

const BATCH = 200
const parts: string[] = []
parts.push(`-- OrgOS demo seed — generated by scripts/export-d1-seed.ts from ${dbPath}`)
parts.push(`-- Apply to Cloudflare D1 (see cloudflare/README.md):`)
parts.push(`--   npx wrangler d1 execute orgos --config wrangler.jsonc --remote --file=cloudflare/seed/seed-demo.sql`)
parts.push(`-- Idempotent: clears all user tables (reverse FK order) before inserting.`)
parts.push('')

// delete children first (reverse topological = safe under FK enforcement)
for (const t of [...order].reverse()) {
  parts.push(`DELETE FROM "${t}";`)
}
parts.push('')

let totalRows = 0
for (const t of order) {
  const tableCols = cols.get(t)!.map((c) => `"${c.name}"`).join(', ')
  const rows = rowsForTable(t)
  totalRows += rows.length
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH)
    const values = batch.map((r) => `(${Object.values(r).map(val).join(', ')})`).join(',\n')
    parts.push(`INSERT INTO "${t}" (${tableCols}) VALUES\n${values};`)
  }
}

parts.push('')
parts.push(`-- total rows: ${totalRows} across ${order.length} tables`)

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, parts.join('\n') + '\n')
console.log(`wrote ${outPath}: ${order.length} tables, ${totalRows} rows, ${parts.length} statements`)
